version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gocritic
    - godoclint
    - godot
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unused
    - wsl_v5
  settings:
    godot:
      scope: declarations
      capital: true
      period: true
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
  exclusions:
    generated: strict
    warn-unused: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/almostinf/postgres-sqlguard
  exclusions:
    generated: strict
    warn-unused: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
